// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LrclibCandidate = {
  track_name: string;
  artist_name: string;
  album_name: string;
  duration_secs: number;
  lines: Array<string>;
};
